import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

export default defineConfig({
  site: 'https://wiki-for-amaranth.pages.dev',
  integrations: [starlight({
    title: 'Amaranth Wiki',
    defaultLocale: 'root',
    locales: {
      root: { label: '简体中文', lang: 'zh-cn' },
    },
    customCss: ['./src/styles/custom.css'],
    sidebar: [
      {
        label: '🏠 首页',
        link: '/',
      },
      {
        label: '☁️ AI云组会',
        collapsed: false,
        items: [
          { label: '总览', link: 'ai-daily/' },
          { label: '今日最新', link: 'ai-daily/2026-08-03' },
          { label: '2026年8月', link: 'ai-daily/08月-2026' },
          { label: '2026年7月', link: 'ai-daily/07月-2026' },
          { label: '2026年6月', link: 'ai-daily/06月-2026' },
        ],
      },
      {
        label: '📄 ArXiv论文日报',
        collapsed: false,
        items: [
          { label: '总览', link: 'papers/' },
          { label: '今日最新', link: 'papers/2026-08-01' },
        ],
      },
      {
        label: '🏗️ 工程汇报',
        collapsed: false,
        items: [
          { label: '总览', link: 'engineering-reports/' },
          { label: 'DeepSeek', link: 'engineering-reports/deepseek/' },
          { label: 'Anthropic', link: 'engineering-reports/anthropic/' },
          { label: 'OpenAI', link: 'engineering-reports/openai/' },
          { label: 'Google DeepMind', link: 'engineering-reports/deepmind/' },
          { label: 'Moonshot AI', link: 'engineering-reports/moonshot/' },
          { label: 'ByteDance Seed', link: 'engineering-reports/bytedance/' },
          { label: 'Qwen (阿里)', link: 'engineering-reports/qwen/' },
          { label: '智谱 AI', link: 'engineering-reports/zhipu/' },
          { label: '小米 MiMo', link: 'engineering-reports/xiaomi/' },
          { label: 'Meta FAIR', link: 'engineering-reports/meta/' },
          { label: 'Mistral AI', link: 'engineering-reports/mistral/' },
          { label: 'MiniMax', link: 'engineering-reports/minimax/' },
        ],
      },
      {
        label: '📦 Skill 分享',
        collapsed: false,
        items: [
          { label: '目录', link: 'skill-share/' },
          { label: '📝 Review Writing', link: 'skill-share/review-writing-profile/' },
          { label: '🔄 Async Delegate', link: 'skill-share/async-delegate-profile/' },
          { label: '🔍 Search Routing', link: 'skill-share/search-routing-profile/' },
          { label: '📱 Social MCP', link: 'skill-share/social-mcp-profile/' },
          { label: '🔮 共振引擎', link: 'skill-share/resonance-engine-profile/' },
          { label: '🛠️ Ops', link: 'skill-share/ops-profile/' },
        ],
      },
      {
        label: '🔧 折腾记录',
        collapsed: false,
        items: [
          { label: '时间线', link: 'notes/tinkering-timeline/' },
          { label: '双向 SSH 互修通道', link: 'notes/bidirectional-ssh-channel/' },
          { label: '📐 实用数学指南', link: 'notes/math-handbook/' },
          { label: '🧠 自然科学哲学世界观', link: 'notes/natural-science-philosophy/' },
          { label: '🌿 枝叶通道', link: 'projects/枝叶通道/' },
          { label: '🖥️ VPS 代替机场', link: 'projects/vps-proxy/' },
          { label: '📐 工程范式学习库', link: 'projects/engineering-learn/' },
        ],
      },
      {
        label: '🆓 白嫖指南',
        collapsed: false,
        items: [
          { label: '商汤 SenseNova 免费 API', link: 'freebies/2026-06-10-sensenova-token-plan/' },
          { label: 'free-for.dev 开发者免费服务', link: 'freebies/free-for-dev/' },
        ],
      },
      {
        label: '🤖 Hermes Agent',
        collapsed: false,
        items: [
          {
            label: '📦 部署',
            collapsed: true,
            items: [
              { label: '概述', link: 'hermes/部署/' },
              { label: '环境准备', link: 'hermes/部署/env-prep/' },
              { label: 'Docker 部署', link: 'hermes/部署/docker-deploy/' },
              { label: '代理配置', link: 'hermes/部署/proxy-setup/' },
              { label: 'GPU 透传', link: 'hermes/部署/gpu-compute/' },
              { label: '验证运行', link: 'hermes/部署/verify/' },
              { label: '断网兜底', link: 'hermes/部署/network-fallback/' },
              { label: '云端生图', link: 'hermes/部署/cloud-image-gen/' },
              { label: 'GPU 训练踩坑', link: 'hermes/部署/gpu-training-pitfalls/' },
            ],
          },
          {
            label: '⚙️ 配置',
            collapsed: true,
            items: [
              { label: '概述', link: 'hermes/配置/' },
              { label: '配置指南', link: 'hermes/配置/configuration/' },
              { label: '多模型路由', link: 'hermes/配置/model-routing/' },
              { label: '技能系统', link: 'hermes/配置/skills/' },
              { label: '持久记忆', link: 'hermes/配置/memory-system/' },
              { label: '定时任务', link: 'hermes/配置/cron-background/' },
              { label: '工作流自动化', link: 'hermes/配置/automation/' },
              { label: '异步任务委派', link: 'hermes/配置/async-delegate/' },
            ],
          },
          {
            label: '🔌 集成',
            collapsed: true,
            items: [
              { label: '概述', link: 'hermes/集成/' },
              { label: '微信接入', link: 'hermes/集成/gateway-wechat/' },
              { label: 'Codex 接入', link: 'hermes/集成/codex-integration/' },
              { label: 'BigSet 集成', link: 'hermes/集成/bigset-integration/' },
              { label: '插件开发', link: 'hermes/集成/plugin-development/' },
            ],
          },
          {
            label: '🔧 运维',
            collapsed: true,
            items: [
              { label: '概述', link: 'hermes/运维/' },
              { label: '服务器配置快照', link: 'hermes/运维/cloud-server-config/' },
              { label: 'CI/CD 自动部署', link: 'hermes/运维/ci-cd/' },
              { label: '完整排障索引', link: 'hermes/运维/troubleshooting-guide/' },
              { label: '排障手册', link: 'hermes/运维/troubleshooting/' },
              { label: '系统架构总览', link: 'hermes/运维/architecture/' },
              { label: '本地 vs 云端', link: 'hermes/运维/cloud-vs-local/' },
              { label: '设计原理摘要', link: 'hermes/运维/design-principles/' },
              { label: 'API 渠道速查', link: 'hermes/运维/api-reference/' },
              { label: '常用命令速查', link: 'hermes/运维/quick-reference/' },
              ],
              },
              {
              label: '📖 官方文档（汉化版）',
              collapsed: true,
              items: [
              { label: '📖 首页', link: 'hermes/官方文档/' },
              { label: '🚀 快速开始', link: 'hermes/官方文档/getting-started/quickstart/' },
              { label: '⚙️ 安装指南', link: 'hermes/官方文档/getting-started/installation/' },
              { label: '📟 CLI 界面', link: 'hermes/官方文档/user-guide/cli/' },
              { label: '🖥️ 桌面应用', link: 'hermes/官方文档/user-guide/desktop/' },
              { label: '📝 配置说明', link: 'hermes/官方文档/user-guide/configuration/' },
              { label: '🧩 功能概览', link: 'hermes/官方文档/user-guide/features/overview/' },
              { label: '📨 消息平台', link: 'hermes/官方文档/user-guide/messaging/index/' },
              { label: '🔗 集成指南', link: 'hermes/官方文档/integrations/index/' },
              { label: '📚 教程', link: 'hermes/官方文档/guides/tips/' },
              { label: '🔧 开发者', link: 'hermes/官方文档/developer-guide/architecture/' },
              { label: '📋 命令参考', link: 'hermes/官方文档/reference/cli-commands/' },
              { label: '❓ FAQ', link: 'hermes/官方文档/reference/faq/' },
              ],
              },
        ],
      },
      {
        label: '📝 博客',
        collapsed: true,
        items: [
          { label: '论文→代码：Lau博士落地实践', link: 'blog/lau-hermes-implementations/' },
          { label: '📊 7月AI趋势（第1周）', link: 'blog/july-2026-trends/' },
          { label: '📊 7月AI趋势（第2-3周）', link: 'blog/july-2026-trends-part2/' },
          { label: '2026 大模型横评', link: 'blog/llm-comparison-2026/' },
          { label: '🤖 AI 信息前沿', link: 'notes/ai-frontier/' },
        ],
      },
      {
        label: '🎮 项目',
        collapsed: true,
        items: [
          { label: 'PPT-Master', link: 'projects/ppt-master/' },
          { label: 'BigSet 部署', link: 'projects/bigset/' },
          { label: '🧰 自定义技能集', link: 'projects/skill-portfolio/' },
          { label: 'ComfyUI 部署与训练', link: 'projects/comfyui/' },
          { label: '🧬 DNA Sim Engine', link: 'projects/dna-sim-engine/' },
          { label: '🔮 共振引擎', link: 'projects/resonance-engine/' },
          { label: '🗺️ Strata — 记忆地层引擎', link: 'guide/strata-intro/' },
          { label: '🪄 Hermes 工具箱', link: 'projects/hermes-toolkit/' },
          { label: '💻 笔记本工作站配置', link: 'projects/笔记本工作站配置日志/' },
          {
            label: '📖 详解',
            collapsed: true,
            items: [
              { label: 'MCP 详解', link: 'projects/mcp-guide/' },
              { label: '命令详解', link: 'projects/commands-guide/' },
            ],
          },
        ],
      },
      {
        label: '🌱 Begonia 协作笔记',
        collapsed: false,
        items: [
          { label: '协作空间', link: 'notes/begonia/' },
          { label: '📋 新人接入灵魂花园', link: 'notes/begonia/notebook-onboard-to-soul-garden/' },
          { label: '🤝 花间协作协议 v1', link: 'notes/begonia/collaboration-protocol-v1/' },
          { label: '🏛️ 灵魂花园架构总览', link: 'notes/begonia/soul-garden-architecture/' },
          { label: '📰 知乎中继协议', link: 'notes/begonia/zhihu-relay-protocol/' },
        ],
      },
    ],
  })],
});
